odaiba-app/server

app/models/classroom.rb
app/models/student_classroom.rb
app/models/student_work_group.rb
app/models/work_group.rb
db/schema.rb
db/seeds.rb

updated seeds

---

.rubocop.yml
Gemfile

Rubocop config

---

spec/controllers/worksheets_controller_spec.rb

based on phone agreement, worksheet will be handled via Node.js

commented out

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/classrooms.scss
app/assets/stylesheets/work_groups.scss
app/assets/stylesheets/worksheets.scss
app/controllers/images_controller.rb
app/helpers/images_helper.rb
app/models/image.rb
app/models/user.rb
app/views/images/new.html.erb
config/environments/development.rb
config/routes.rb
config/storage.yml
db/migrate/20200722060124_create_active_storage_tables.active_storage.rb
db/migrate/20200722064227_create_images.rb
db/schema.rb
public/packs/manifest.json
spec/controllers/images_controller_spec.rb
spec/helpers/images_helper_spec.rb
spec/models/classroom_spec.rb
spec/models/image_spec.rb
spec/models/user_spec.rb
spec/models/work_group_spec.rb

@dzakki 
you can test upload feature from server side: 
- go to localhost:3000/images/new
- select image from pc and submit
- see rendered json with url

set up cloudinary

---

app/models/student_classroom.rb

Changed styling to be the same as the classroom model for validation

Student classroom

---

app/models/student_work_group.rb

Added user validation to student_work_group model

made Teacher unable to create student work group

---

app/models/work_group.rb

Added all validations to Work_group

Work group validations

---

app/models/user.rb

Added validations for User model

added presence validation to role and name for user

---

app/models/worksheet_template.rb

passed worksheet template rspec tests

added user role and title validation to worksheet template

---

app/models/worksheet.rb

Passed tests for worksheet model

added canvas and title validation to worksheet

---

app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
config/routes.rb

Don't know how to fix the input area not covering the whole white part. Maybe some of you can figure it out later

root to login from odaiba

---

Gemfile
Gemfile.lock
app/controllers/api/v1/work_groups_controller.rb

Add turn time to json

---

.rspec
public/packs/manifest.json

Changed the variable 'Progress' to 'progress' in .rspec

Hotfix rspec

---

script/create_instances_for_demo.rb

When demoing the app, I need to create new users and all the relevant instances, which takes a lot of time.
This script helps speed up the process, just run `rails runner script/create_instances_for_demo.rb`

script for demo

---

app/controllers/api/v1/worksheet_templates_controller.rb
app/controllers/api/v1/worksheets_controller.rb
app/services/cloudinary_uploader.rb
script/create_instances_for_demo.rb
spec/services/cloudinary_uploader_spec.rb

in the demo we found that we couldn't just point to a foreign image url as the worksheet would not display, so we always have to point to cloudinary
since we need to make sure the url is correct in different places of our codebase I went forward and created a service that covers this
please review and merge

Cloudinary uploader

---

app/models/user.rb

Added the teachers method for User. If there are alternatives or improved ways to approach this please let me know!

Added teachers method for User

---

package.json

```
"scripts": {
"dbreset": "rails db:drop db:create db:migrate db:seed"
},
```
added script db reset at package.json. so that i can run `rails db:drop db:create db:migrate db:seed` with `npm run dbreset`

added script dbreset

---

app/controllers/api/v1/base_controller.rb

merging for urgency, but feel free to ask

changed from 401 to 403

---

spec/controllers/api/v1/classrooms_controller_spec.rb
spec/controllers/api/v1/work_groups_controller_spec.rb
spec/controllers/api/v1/worksheet_templates_controller_spec.rb
spec/controllers/api/v1/worksheets_controller_spec.rb

merging for urgency, but please still check

fixed tests

---

app/controllers/api/v1/worksheet_templates_controller.rb
app/controllers/api/v1/worksheets_controller.rb
spec/controllers/api/v1/worksheets_controller_spec.rb

Fixed the Worksheets Controller tests

Worksheets controller

---

app/controllers/work_groups_controller.rb
app/mailers/invitation_mailer.rb
app/services/work_group_demo_prepper.rb
app/views/work_groups/new.html.erb
config/routes.rb
spec/controllers/work_groups_controller_spec.rb
spec/views/work_groups/create.html.erb_spec.rb
spec/views/work_groups/new.html.erb_spec.rb

big feature implemented
essentially I need to provide our partner/mentor with a link which he could use to create sessions and invite interested people
I've used /work_groups/new for that purpose, and after inputting the data emails get sent
@francescheng I need to ask you to urgently work on the mailer template and the form in the view mentioned above. DM me if you are lost or don't think you can handle it

Self workgroup demo creation screen

---

app/helpers/email_helper.rb
app/mailers/invitation_mailer.rb
app/views/invitation_mailer/demo_invite.html.erb
app/views/layouts/mailer.html.erb
public/packs/manifest.json
spec/mailers/previews/invitation_mailer_preview.rb

Darkened header to match the logo image, but the logo image is still not there

Mailer style

---

app/helpers/email_helper.rb
app/mailers/invitation_mailer.rb
app/views/invitation_mailer/demo_invite.html.erb
app/views/layouts/mailer.html.erb

removed email helper, changed logo size

---

app/views/layouts/mailer.html.erb

removed underlines from links

---

app/mailers/invitation_mailer.rb
app/views/layouts/mailer.html.erb

Just took out some commented lines

removed some commented out lines

---

app/controllers/api/v1/work_groups_controller.rb
app/models/work_group.rb
app/services/work_group_demo_prepper.rb

going to merge due to urgency, but there definitely will be a new version with better code so be sure to review this and more to come

return active workgroups

---

app/models/work_group.rb

here is the refactored version of the PR
some tests might be failing due to this so will need to look into that

refactoring

---

app/views/invitation_mailer/demo_invite.html.erb

minor styling changes

---

app/models/classroom.rb
spec/controllers/api/v1/classrooms_controller_spec.rb
spec/models/classroom_spec.rb
spec/support/factories/classrooms.rb

Updated the classroom factory bot and added tests. Please let me know what I missed! Thank you!

Classrooms tests for start/end time

---

app/controllers/api/v1/classrooms_controller.rb
spec/controllers/api/v1/classrooms_controller_spec.rb

I'm not quite sure if this is the best way to approach this, but I gave it a try! Please let me know if there are better ways to do it. Thank you!

updated JSON output to show class_time method for Classroom Class

---

app/controllers/work_groups_controller.rb
app/models/classroom.rb
app/models/work_group.rb
config/application.rb
config/sitemap.rb
db/seeds.rb
script/create_instances_for_demo.rb
spec/controllers/api/v1/classrooms_controller_spec.rb
spec/controllers/api/v1/work_groups_controller_spec.rb
spec/models/classroom_spec.rb
spec/models/work_group_spec.rb
spec/support/factories/work_groups.rb

changes to timezone based on this article: http://www.samir-el-maoujoudi.com/code/2018/10/12/how-to-handle-time-zones-in-rails.html

change time zone

---

app/controllers/work_groups_controller.rb
app/views/work_groups/new.html.erb

would be good if flatpickr would give default value of today's date

fixed params

---

app/controllers/work_groups_controller.rb
app/views/work_groups/new.html.erb
public/packs/manifest.json

clear validations

---

db/seeds.rb

need to make sure that Classroom with ID 1 always belongs to User with ID 1
plus some minor changes to generated worksheets

updated seeds:

---

app/controllers/api/v1/classrooms_controller.rb
app/models/user.rb

merging for urgency, feel free to leave your comments if something is unclear
tests will need to be added and fixed

active_student_workgroups

---

app/controllers/api/v1/base_controller.rb
app/controllers/work_groups_controller.rb

solving issue https://github.com/odaiba-app/server/issues/118
This code used to be suggested by LW's lecture on building an API, but I recheck just now and it was removed, so I'm removing it from our codebase too

Remove rescue from standard error

---

app/assets/stylesheets/pages.scss
app/javascript/packs/application.js
app/views/work_groups/new.html.erb
db/schema.rb
public/packs/manifest.json

Work groups page

---

app/models/student_classroom.rb

Sorry, but you can't see anything I changed because git is behaving weirdly. In order to convince git to actually push this, because for some reason it can't detect the changes I made, I had to make a meaningless comment and delete it. The changes are there, though.

Add uniqness validation student in workgroup

---

app/controllers/api/v1/worksheets_controller.rb
app/models/work_group.rb
db/migrate/20201015135428_add_worksheet_email_sent_column_to_work_groups.rb
db/schema.rb
spec/models/work_group_spec.rb

just had a session where we both kept our app open and received 2 emails with the final worksheet
creating a column to avoid this from happening

send worksheet email only once

---

app/policies/work_group_policy.rb
app/views/work_groups/new.html.erb
public/packs/manifest.json

aasm policy

---

spec/mailers/demo_mailer_spec.rb

I'm not sure if I covered everything, so please let me know!

Added tests for sending worksheets in mailer

---

app/controllers/api/v1/worksheets_controller.rb

merging for urgent deploy, but feel free to add your questions

worksheet mailer hotfix

---

app/assets/stylesheets/pages.scss
app/controllers/work_groups_controller.rb
app/javascript/packs/application.js
app/views/work_groups/new.html.erb

Links are now orange, also added an error message if copy doesn't work

List generated links

---

app/javascript/packs/application.js
public/packs/manifest.json

Removed the try/catch err code to fix copy function

Remove err

---

app/services/classroom_demo_prepper.rb
app/services/students_demo_prepper.rb

bugfix user email prepper

---

app/controllers/work_groups_controller.rb
app/views/shared/_modal.html.erb
app/views/work_groups/new.html.erb

in the collab session creation screen we used to give the option to choose turn time length
now we set up default 1 minute

remove turn timer

---

app/controllers/api/v1/base_controller.rb
app/controllers/work_groups_controller.rb

debugging of workgroup controller

---

spec/mailers/demo_mailer_spec.rb

fix a few failing mailer tests, didn't check coverage to add more

fix mailer tests

---

app/controllers/api/v1/worksheets_controller.rb

fix worksheet index

---

app/assets/stylesheets/pages.scss

added pointer and hover style to button

---

Gemfile
Gemfile.lock
app/controllers/api/v1/classrooms_controller.rb
app/controllers/api/v1/work_groups_controller.rb
app/models/work_group.rb
app/views/api/v1/classrooms/show.json.jbuilder
app/views/api/v1/work_groups/show.json.jbuilder
spec/controllers/api/v1/classrooms_controller_spec.rb

Also added rubocop to gemfile.

Updated work_group controller to use jbuilder instead of deep_pluck
